server:
  port: 1111
  
# Specify application name
spring:
  application:
    name: zuul-api-gateway

# Declare producers
zuul:
  routes:
    producer:
      url: http://localhost:8080
      
# Registry to eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka