spring:
  application:
    name: employee-consumer

# Specify application name
server:
  port: 9090

# Registry to eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka